dependencies:
  # - <organaziton/repo>@<version>
  # 安装依赖包 使用能有npm包导入的版本
  - smartcontractkit/chainlink-brownie-contracts@1.2.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.2.0"
dotenv: .env
networks:
  development:
    verify: False
  ganache-local:
    verify: False
  sepolia:
    eth_usd_price_feed: "0x694AA1769357215DE4FAC081bf1f309aDC325306"
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  minnet:
    verify: True # 空白变量被编译成非类型，这会导致错误
wallets:
  from_key: ${PRIVATE_KEY}
